apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: kube-prometheus-stack
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 45.0.0
    helm:
      values: |
        prometheus:
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
        prometheusOperator:
           admissionWebhooks:
             failurePolicy: Ignore
  destination:
    server: https://kubernetes.default.svc
    namespace: mons

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    automated:
      selfHeal: true
      prune: true