{{- if .Values.unsecuredSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: mysql-secrets
    namespace: default
type: Opaque
data:
    app-db-user: dGVzdHVzZXI=
    mysql-root-password: dGVzdHJvb3RwYXNz
    mysql-replication-password: dGVzdHBhc3M=
    mysql-password: dGVzdHBhc3M=
{{- end}}