apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.globl.appName }}-config
  namespace: {{ .Values.globl.namespace }}
data:
  mysql-host: "{{ .Release.Name }}-mysql-primary-headless"
  mysql-database: dressify