apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.globl.appName }}-svc
  namespace: {{ .Values.globl.namespace }}
  labels:
    app: {{ .Values.globl.appName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.globl.appName }}
  ports:
    - name: web 
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}