{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Values.globl.namespace }}
spec:
  acme:
    email: {{ .Values.issuer.mail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.issuer.name }}
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end}}